apiVersion: v1
kind: Pod
metadata:
  name: http-server
spec:
  terminationGracePeriodSeconds: 60
  containers:
    - name: http-server
      image: mdeng2022/http-server
      readinessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5          
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
      resources:  
        requests:    
          cpu: 50m
          memory: 50Mi
        limits:    
          cpu: 100m
          memory: 500Mi