apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app: http-server
  annotations:
    prometheus.io/port: http-metrics
    prometheus.io/scrape: "true"
spec:
  containers:
    - name: http-server
      image: mdeng2022/http-server:1.0
      ports:
      - containerPort: 80
        name: http-metrics
        protocol: TCP
